// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { signInWithCustomToken } from "firebase/auth";
import { auth } from "../firebase/config";

const lovableAuth = createLovableAuth({});

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        // Note: Firebase requires custom token authentication for OAuth
        // You may need to implement a backend endpoint to exchange tokens
        console.warn('OAuth integration with Firebase requires custom token exchange');
        return { error: new Error('OAuth not fully configured for Firebase') };
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
    },
  },
};
